### ISSUE TITLE
Missions on bfa.wowhead.com

### ISSUE THREAD

**Issue by Suraf** [Maia-Everett/wet#1]
Missions on bfa.wowhead don't load.

Originally posted by Mordecay:
https://wow.gamepedia.com/Wowpedia_talk:Wowpedia_Editor%27s_Toolkit#PTR

**Comment by Maia-Everett** [comment]
Every type of mission (garrison, naval, Legion, BfA) requires separate handling. If you link me an example of a BfA mission article on Wowpedia, I can implement parsing them.
