### ISSUE TITLE
Rebrand: Warcraft Wiki

### ISSUE THREAD

**Issue by Suraf** [Maia-Everett/wet#39]
https://warcraft.wiki.gg/wiki/Warcraft_Wiki:Warcraft_Wiki_Editor's_Toolkit

**Comment by Maia-Everett** [comment]
On it!

**Comment by Maia-Everett** [comment]
Released in 2.0.14.

**Comment by Suraf** [comment]
This tool is invaluable to myself and some of the other power editors at Warcraft Wiki (formerly Wowpedia). Much appreciated! 😄
